#!/Users/spence/.cache/pre-commit/repo51vvjcpn/py_env-python3/bin/python

import re, sys, subprocess, os

BRANCH_COMMAND = ("git", "rev-parse", "--abbrev-ref", "HEAD")
EXAMPLE_ID = "EXAMPLE-123"
FILE = sys.argv[1]

if __name__ == "__main__":
    if os.environ.get("GIT_EDITOR") == ":":
        exit()

    branch_cmd = subprocess.run(BRANCH_COMMAND, stdout=subprocess.PIPE)
    id = re.search(r"(^\w+-\w+)", str(branch_cmd.stdout))
    id = id.groups(EXAMPLE_ID)[1] if id else EXAMPLE_ID


    with open(FILE) as fh:
        msg = fh.readlines()
        if id == EXAMPLE_ID:
            if os.environ.get('JIRA_PROJECTS'):
                instr = f"\n\n# All commit messages must be prefixed with their jira card ids.\n# e.g. `EXAMPLE-123: ` replacing EXAMPLE with any of the following {os.environ.get('JIRA_PROJECTS')}\n#"
            else:
                instr = f"\n\n# All commit messages must be prefixed with their jira card ids.\n# e.g. `EXAMPLE-123: \n#`"
        else:
            instr = f"\n\n# All commit messages must be prefixed with their jira card ids.\n#\n#"

    msg.insert(0, instr)

    with open(FILE, "w") as fh:
        fh.write("".join(msg))
